// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ToCatchAGremlin.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CrimeDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfCharge")
                        .HasColumnType("datetime2");

                    b.Property<int>("GremlinId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GremlinId");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("Gremlin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JailHouseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JailHouseId");

                    b.ToTable("Gremlins");
                });

            modelBuilder.Entity("JailHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jails");
                });

            modelBuilder.Entity("Charge", b =>
                {
                    b.HasOne("Gremlin", "Gremlin")
                        .WithMany("Charges")
                        .HasForeignKey("GremlinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gremlin");
                });

            modelBuilder.Entity("Gremlin", b =>
                {
                    b.HasOne("JailHouse", "JailHouse")
                        .WithMany("Gremlins")
                        .HasForeignKey("JailHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JailHouse");
                });

            modelBuilder.Entity("Gremlin", b =>
                {
                    b.Navigation("Charges");
                });

            modelBuilder.Entity("JailHouse", b =>
                {
                    b.Navigation("Gremlins");
                });
#pragma warning restore 612, 618
        }
    }
}
